language: node_js
version: 1.0
dist: focal
node_js:
- '14'
- '15'
- '16'
script: node index.js
deploy:
  edge: true
  provider: npm
  email: developers@qarnot.com
  api_key:
    secure: O41y7pa3VGQ/0d43RHEGI+LEVuvVUJjPRjkkabGCijQd16Ro42ktkjNjC82wrnrLNgnbcZIl3LmexLbP4RTFyta1T+zTgPloQmDUKQFCYIJ6BBbSxae8T+YUihyhWIwpCkg+aGs0/uyjwK/4AfNkP3UEPhx08hmj2a8u5MOcbEzix5hvviR/hSASsHub05140tzyLsbN+L0UvhtaCnAKs7S9kFvfBSEvClYvA76k9OprWoo9Mm5nypulT3DIkODMY1PEpr62nyzm//L/hAaM7+A145NOZ+RWOyLEdimvyyOPpL2qGak/YC3QokiQoHvzkot/lPFuoCuG0sd9nMm3JNjvJHhUWACRP3+aDAzNmV2uiP38EX51RPwCAfhxdVENmFQYkliXe9PDL9rKH3QwmNOkHVDOc/wfEz3eK2+TVnYnxJOCiCUdLwQG5O+cWJtVOr+W5SU8kDYHNPcgw8XRcZkjejAe6gM2AgIW9BwcD/2z4uZWlqXhYJezGu3Hd/ZREoZyJrnRc1b4iuKLH488PlN247WE17iR1zvkr3k+Xz89WvvKPTu/lwAckTAyDT6dyyy4c3TnDTbAkKubjMRY+LGouqbmEo0Qn+n2vXCfJ6JCluKDwDvTEbvvTtcYxalE0dEwMAsbqpaIt1tRJUlHEHAjjrbjjBTqMVl3ktqyO4k=
  on:
    tags: true
    branch: master
